<?php
declare(strict_types=1);

// Bud SDK utility registration

require_once __DIR__ . '/../core/UtilityType.php';
require_once __DIR__ . '/Clean.php';
require_once __DIR__ . '/Done.php';
require_once __DIR__ . '/MakeError.php';
require_once __DIR__ . '/FeatureAdd.php';
require_once __DIR__ . '/FeatureHook.php';
require_once __DIR__ . '/FeatureInit.php';
require_once __DIR__ . '/Fetcher.php';
require_once __DIR__ . '/MakeFetchDef.php';
require_once __DIR__ . '/MakeContext.php';
require_once __DIR__ . '/MakeOptions.php';
require_once __DIR__ . '/MakeRequest.php';
require_once __DIR__ . '/MakeResponse.php';
require_once __DIR__ . '/MakeResult.php';
require_once __DIR__ . '/MakePoint.php';
require_once __DIR__ . '/MakeSpec.php';
require_once __DIR__ . '/MakeUrl.php';
require_once __DIR__ . '/Param.php';
require_once __DIR__ . '/PrepareAuth.php';
require_once __DIR__ . '/PrepareBody.php';
require_once __DIR__ . '/Graphql.php';
require_once __DIR__ . '/PrepareHeaders.php';
require_once __DIR__ . '/PrepareMethod.php';
require_once __DIR__ . '/PrepareParams.php';
require_once __DIR__ . '/PreparePath.php';
require_once __DIR__ . '/PrepareQuery.php';
require_once __DIR__ . '/ResultBasic.php';
require_once __DIR__ . '/ResultBody.php';
require_once __DIR__ . '/ResultHeaders.php';
require_once __DIR__ . '/TransformRequest.php';
require_once __DIR__ . '/TransformResponse.php';

BudUtility::setRegistrar(function (BudUtility $u): void {
    $u->clean = [BudClean::class, 'call'];
    $u->done = [BudDone::class, 'call'];
    $u->make_error = [BudMakeError::class, 'call'];
    $u->feature_add = [BudFeatureAdd::class, 'call'];
    $u->feature_hook = [BudFeatureHook::class, 'call'];
    $u->feature_init = [BudFeatureInit::class, 'call'];
    $u->fetcher = [BudFetcher::class, 'call'];
    $u->make_fetch_def = [BudMakeFetchDef::class, 'call'];
    $u->make_context = [BudMakeContext::class, 'call'];
    $u->make_options = [BudMakeOptions::class, 'call'];
    $u->make_request = [BudMakeRequest::class, 'call'];
    $u->make_response = [BudMakeResponse::class, 'call'];
    $u->make_result = [BudMakeResult::class, 'call'];
    $u->make_point = [BudMakePoint::class, 'call'];
    $u->make_spec = [BudMakeSpec::class, 'call'];
    $u->make_url = [BudMakeUrl::class, 'call'];
    $u->param = [BudParam::class, 'call'];
    $u->prepare_auth = [BudPrepareAuth::class, 'call'];
    $u->prepare_body = [BudPrepareBody::class, 'call'];
    $u->prepare_headers = [BudPrepareHeaders::class, 'call'];
    $u->prepare_method = [BudPrepareMethod::class, 'call'];
    $u->prepare_params = [BudPrepareParams::class, 'call'];
    $u->prepare_path = [BudPreparePath::class, 'call'];
    $u->prepare_query = [BudPrepareQuery::class, 'call'];
    $u->graphql_body = [BudGraphql::class, 'body'];
    $u->graphql_errors = [BudGraphql::class, 'errors'];
    $u->result_basic = [BudResultBasic::class, 'call'];
    $u->result_body = [BudResultBody::class, 'call'];
    $u->result_headers = [BudResultHeaders::class, 'call'];
    $u->transform_request = [BudTransformRequest::class, 'call'];
    $u->transform_response = [BudTransformResponse::class, 'call'];
});
